/*
 * Twelve Data API client for Java
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * WebSocket client for streaming real-time prices from Twelve Data.
 *
 * <p>The entry point is {@link com.twelvedata.client.ws.TwelvedataWebSocketClient}.
 * Configure it with {@link com.twelvedata.client.ws.TwelvedataWebSocketOptions}
 * (or rely on defaults plus the {@code TWELVEDATA_API_KEY} env variable),
 * register a {@link com.twelvedata.client.ws.TwelvedataWebSocketListener},
 * call {@code connect()} and then {@code subscribe(...)}.</p>
 *
 * <p>The client handles authorization, application-level heartbeats and
 * protocol-level pings, dead-connection detection, and automatic reconnection
 * with exponential backoff. Active subscriptions are replayed automatically
 * after a reconnect.</p>
 */
package com.twelvedata.client.ws;
