/*
 * Twelve Data API client for Java
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twelvedata.client.ws;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Real-time price tick event from the Twelve Data WebSocket stream
 * ({@code event:"price"}).
 *
 * <p>Server-side fields not modeled here are preserved in {@link #getAdditionalFields()}
 * so the client tolerates new fields without a release.</p>
 */
@JsonIgnoreProperties(ignoreUnknown = false)
public class PriceEvent {

    private String event;
    private String symbol;
    private String currency;

    @JsonProperty("currency_base")
    private String currencyBase;

    @JsonProperty("currency_quote")
    private String currencyQuote;

    private String exchange;

    @JsonProperty("mic_code")
    private String micCode;

    private String type;
    private long timestamp;
    private double price;
    private Double bid;
    private Double ask;

    @JsonProperty("day_volume")
    private Long dayVolume;

    private final Map<String, Object> additionalFields = new LinkedHashMap<>();

    public String getEvent() {
        return event;
    }

    public void setEvent(String event) {
        this.event = event;
    }

    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getCurrencyBase() {
        return currencyBase;
    }

    public void setCurrencyBase(String currencyBase) {
        this.currencyBase = currencyBase;
    }

    public String getCurrencyQuote() {
        return currencyQuote;
    }

    public void setCurrencyQuote(String currencyQuote) {
        this.currencyQuote = currencyQuote;
    }

    public String getExchange() {
        return exchange;
    }

    public void setExchange(String exchange) {
        this.exchange = exchange;
    }

    public String getMicCode() {
        return micCode;
    }

    public void setMicCode(String micCode) {
        this.micCode = micCode;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public Double getBid() {
        return bid;
    }

    public void setBid(Double bid) {
        this.bid = bid;
    }

    public Double getAsk() {
        return ask;
    }

    public void setAsk(Double ask) {
        this.ask = ask;
    }

    public Long getDayVolume() {
        return dayVolume;
    }

    public void setDayVolume(Long dayVolume) {
        this.dayVolume = dayVolume;
    }

    /** Server-side fields that don't have a typed getter. */
    @JsonAnyGetter
    public Map<String, Object> getAdditionalFields() {
        return additionalFields;
    }

    @JsonAnySetter
    public void setAdditionalField(String name, Object value) {
        additionalFields.put(name, value);
    }

    @Override
    public String toString() {
        return "PriceEvent{symbol=" + symbol
                + ", price=" + price
                + ", timestamp=" + timestamp
                + (bid != null ? ", bid=" + bid : "")
                + (ask != null ? ", ask=" + ask : "")
                + (exchange != null ? ", exchange=" + exchange : "")
                + "}";
    }
}
