/*
 * Twelve Data API client for Java
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twelvedata.client.ws;

/** Payload delivered to {@link TwelvedataWebSocketListener#onReconnecting} before each retry attempt. */
public final class ReconnectingEvent {

    private final int attempt;
    private final long delayMs;

    public ReconnectingEvent(int attempt, long delayMs) {
        this.attempt = attempt;
        this.delayMs = delayMs;
    }

    /** 1-based attempt number for the upcoming reconnect. */
    public int getAttempt() {
        return attempt;
    }

    /** Delay before the upcoming reconnect attempt is made, in milliseconds. */
    public long getDelayMs() {
        return delayMs;
    }

    @Override
    public String toString() {
        return "ReconnectingEvent{attempt=" + attempt + ", delayMs=" + delayMs + "}";
    }
}
