/*
 * Twelve Data API client for Java
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twelvedata.client.ws;

/** Payload delivered to {@link TwelvedataWebSocketListener#onReconnect} after a successful reconnect. */
public final class ReconnectEvent {

    private final int attempt;

    public ReconnectEvent(int attempt) {
        this.attempt = attempt;
    }

    /** 1-based attempt number that succeeded. */
    public int getAttempt() {
        return attempt;
    }

    @Override
    public String toString() {
        return "ReconnectEvent{attempt=" + attempt + "}";
    }
}
