/*
 * Twelve Data API client for Java
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twelvedata.client.ws;

/**
 * Reconnect strategy for {@link TwelvedataWebSocketClient}.
 *
 * <p>Pass {@code null} to {@link TwelvedataWebSocketOptions.Builder#reconnect(ReconnectOptions)}
 * to disable automatic reconnection entirely.</p>
 *
 * <p>Defaults are read from {@link WebSocketConstants}.</p>
 */
public final class ReconnectOptions {

    private final long initialDelayMs;
    private final long maxDelayMs;
    private final int maxAttempts;
    private final double backoffFactor;

    private ReconnectOptions(Builder b) {
        this.initialDelayMs = b.initialDelayMs;
        this.maxDelayMs = b.maxDelayMs;
        this.maxAttempts = b.maxAttempts;
        this.backoffFactor = b.backoffFactor;
    }

    public long getInitialDelayMs() {
        return initialDelayMs;
    }

    public long getMaxDelayMs() {
        return maxDelayMs;
    }

    public int getMaxAttempts() {
        return maxAttempts;
    }

    public double getBackoffFactor() {
        return backoffFactor;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {

        private long initialDelayMs = WebSocketConstants.DEFAULT_RECONNECT_INITIAL_DELAY_MS;
        private long maxDelayMs = WebSocketConstants.DEFAULT_RECONNECT_MAX_DELAY_MS;
        private int maxAttempts = WebSocketConstants.DEFAULT_RECONNECT_MAX_ATTEMPTS;
        private double backoffFactor = WebSocketConstants.DEFAULT_RECONNECT_BACKOFF_FACTOR;

        public Builder initialDelayMs(long v) {
            this.initialDelayMs = v;
            return this;
        }

        public Builder maxDelayMs(long v) {
            this.maxDelayMs = v;
            return this;
        }

        /** Set to {@link Integer#MAX_VALUE} to retry effectively forever. */
        public Builder maxAttempts(int v) {
            this.maxAttempts = v;
            return this;
        }

        public Builder backoffFactor(double v) {
            this.backoffFactor = v;
            return this;
        }

        public ReconnectOptions build() {
            return new ReconnectOptions(this);
        }
    }
}
