/*
 * Twelve Data API client for Java
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twelvedata.client.ws;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * Extended subscription descriptor for {@link TwelvedataWebSocketClient#subscribe}.
 *
 * <p>Use this when a bare ticker is ambiguous and you need to disambiguate by
 * exchange, MIC code, or instrument type. Bare strings are also accepted by
 * {@code subscribe} / {@code unsubscribe}, so reach for {@code SubscribeSymbol}
 * only when you need the extra fields.</p>
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class SubscribeSymbol {

    private final String symbol;
    private final String exchange;

    @JsonProperty("mic_code")
    private final String micCode;

    private final String type;

    public SubscribeSymbol(String symbol) {
        this(symbol, null, null, null);
    }

    public SubscribeSymbol(String symbol, String exchange, String micCode, String type) {
        if (symbol == null || symbol.isEmpty()) {
            throw new IllegalArgumentException("symbol must not be null or empty");
        }
        this.symbol = symbol;
        this.exchange = exchange;
        this.micCode = micCode;
        this.type = type;
    }

    public String getSymbol() {
        return symbol;
    }

    public String getExchange() {
        return exchange;
    }

    @JsonProperty("mic_code")
    public String getMicCode() {
        return micCode;
    }

    public String getType() {
        return type;
    }

    /**
     * Stable string key used by the client to dedup subscriptions across input
     * forms (bare string vs object). Two {@code SubscribeSymbol}s with equal
     * fields produce the same key.
     */
    String canonicalKey() {
        return "o:" + safe(symbol) + "|" + safe(exchange) + "|" + safe(micCode) + "|" + safe(type);
    }

    private static String safe(String s) {
        return s == null ? "" : s;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SubscribeSymbol)) return false;
        SubscribeSymbol that = (SubscribeSymbol) o;
        return Objects.equals(symbol, that.symbol)
                && Objects.equals(exchange, that.exchange)
                && Objects.equals(micCode, that.micCode)
                && Objects.equals(type, that.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, exchange, micCode, type);
    }

    @Override
    public String toString() {
        return "SubscribeSymbol{symbol=" + symbol
                + ", exchange=" + exchange
                + ", micCode=" + micCode
                + ", type=" + type + "}";
    }
}
