/*
 * Twelve Data API client for Java
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twelvedata.client.ws;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Status event returned in response to a {@code subscribe} or {@code unsubscribe}
 * action. {@link #getSuccess()} and {@link #getFails()} are guaranteed
 * non-{@code null} — the dispatcher coerces server-side {@code null} arrays to
 * an empty list so callers can iterate without a {@code null} check.
 */
public class SubscribeStatusEvent {

    private String event;
    private String status;
    private List<SubscribeStatusItem> success = new ArrayList<>();
    private List<SubscribeStatusItem> fails = new ArrayList<>();

    private final Map<String, Object> additionalFields = new LinkedHashMap<>();

    public String getEvent() {
        return event;
    }

    public void setEvent(String event) {
        this.event = event;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public List<SubscribeStatusItem> getSuccess() {
        return success;
    }

    public void setSuccess(List<SubscribeStatusItem> success) {
        this.success = success != null ? success : new ArrayList<>();
    }

    public List<SubscribeStatusItem> getFails() {
        return fails;
    }

    public void setFails(List<SubscribeStatusItem> fails) {
        this.fails = fails != null ? fails : new ArrayList<>();
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalFields() {
        return additionalFields;
    }

    @JsonAnySetter
    public void setAdditionalField(String name, Object value) {
        additionalFields.put(name, value);
    }

    @Override
    public String toString() {
        return "SubscribeStatusEvent{status=" + status
                + ", success=" + success
                + ", fails=" + fails + "}";
    }
}
