/*
 * Twelve Data API client for Java
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twelvedata.client.ws;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpResponse;
import java.net.http.WebSocket;
import java.net.http.WebSocketHandshakeException;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.ThreadFactory;
import java.util.concurrent.TimeUnit;

/**
 * Twelvedata WebSocket client for streaming real-time prices.
 *
 * <p>Wraps the JDK {@link java.net.http.WebSocket} to provide:
 * <ul>
 *   <li>Listener-based event surface ({@link TwelvedataWebSocketListener}).</li>
 *   <li>Application-level heartbeat ({@code {"action":"heartbeat"}}).</li>
 *   <li>WebSocket-protocol ping/pong with timeout-based dead-connection detection.</li>
 *   <li>Automatic reconnection with exponential backoff and ±20% jitter.</li>
 *   <li>Automatic re-subscription to active symbols after a reconnect.</li>
 * </ul>
 *
 * <p>The API key is taken from the first non-empty value of: the explicit
 * {@link TwelvedataWebSocketOptions.Builder#apiKey} option, or the
 * {@code TWELVEDATA_API_KEY} environment variable. The constructor throws
 * {@link TwelvedataWebSocketException.AuthException} synchronously if neither
 * provides a key.</p>
 */
public class TwelvedataWebSocketClient {

    private static final String API_KEY_ENV_VAR = "TWELVEDATA_API_KEY";

    /**
     * Hard ceiling on a single {@code buildAsync} call. The JDK's
     * {@code HttpClient}-based WebSocket has no built-in handshake timeout, so
     * a stuck server or half-broken connection can hang the future forever.
     * After this deadline we treat the attempt as failed and reschedule.
     */
    private static final long HANDSHAKE_TIMEOUT_MS = 30_000L;

    private final String apiKey;
    private final String url;
    private final long heartbeatIntervalMs;
    private final long pingIntervalMs;
    private final long pingTimeoutMs;
    private final ResolvedReconnectConfig reconnectConfig;

    private final HttpClient httpClient;
    private final ScheduledExecutorService scheduler;
    private final ObjectMapper mapper;
    private final List<TwelvedataWebSocketListener> listeners = new CopyOnWriteArrayList<>();

    /**
     * Tracked subscriptions keyed by canonical form so a bare {@code "AAPL"} and
     * an extended {@code SubscribeSymbol(symbol="AAPL")} dedup to one entry.
     * {@code LinkedHashMap} preserves replay order; wrapped in
     * {@link Collections#synchronizedMap} for cross-thread safety.
     */
    private final Map<String, Object> subscriptions =
            Collections.synchronizedMap(new LinkedHashMap<>());

    private final Object stateLock = new Object();
    /** Single-text-message reassembly buffer (guarded by stateLock; only touched on scheduler thread in practice). */
    private final StringBuilder textBuffer = new StringBuilder();

    private volatile WebSocket socket;
    private volatile boolean userInitiatedClose;
    /** True once the socket has ever reached OPEN. Gates auto-reconnect. */
    private volatile boolean hasEverConnected;
    /**
     * Reference to the listener bound to the in-flight (or current) socket.
     * Stale listener callbacks — e.g. an {@code onOpen} that arrives after the
     * handshake-timeout has already moved us on to the next attempt — are
     * dropped via {@code currentListener != this} checks inside the listener.
     */
    private volatile InternalListener currentListener;
    /** Set when an unrecoverable error occurs (e.g. invalid API key). Suppresses reconnect. */
    private volatile TwelvedataWebSocketException fatalError;
    /** In-flight {@code connect()} future so concurrent calls fold into one. */
    private volatile CompletableFuture<Void> connectingFuture;
    private volatile int reconnectAttempts;

    private volatile ScheduledFuture<?> heartbeatTask;
    private volatile ScheduledFuture<?> pingTask;
    private volatile ScheduledFuture<?> pongDeadline;
    private volatile ScheduledFuture<?> reconnectTask;

    public TwelvedataWebSocketClient() {
        this(TwelvedataWebSocketOptions.builder().build());
    }

    public TwelvedataWebSocketClient(TwelvedataWebSocketOptions options) {
        String resolvedKey = firstNonEmpty(options.getApiKey(), System.getenv(API_KEY_ENV_VAR));
        if (resolvedKey == null) {
            throw new TwelvedataWebSocketException.AuthException(
                    API_KEY_ENV_VAR + " environment variable is not set and no apiKey option was provided");
        }
        this.apiKey = resolvedKey;
        this.url = options.getUrl();
        this.heartbeatIntervalMs = options.getHeartbeatIntervalMs();
        this.pingIntervalMs = options.getPingIntervalMs();
        this.pingTimeoutMs = options.getPingTimeoutMs();
        this.reconnectConfig = ResolvedReconnectConfig.from(options.getReconnect());

        this.httpClient = HttpClient.newHttpClient();
        // Daemon scheduler so a dangling client doesn't keep the JVM alive — the
        // Java equivalent of `unref()`-ing each timer in the Node reference.
        this.scheduler = Executors.newSingleThreadScheduledExecutor(daemonThreadFactory());
        this.mapper = new ObjectMapper()
                .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
                .setDefaultPropertyInclusion(JsonInclude.Include.NON_NULL);
    }

    public void addListener(TwelvedataWebSocketListener listener) {
        if (listener != null) listeners.add(listener);
    }

    public void removeListener(TwelvedataWebSocketListener listener) {
        listeners.remove(listener);
    }

    /**
     * Open the WebSocket connection. Resolves on the first {@code onOpen}, completes
     * exceptionally if the very first attempt fails. Background reconnects after a
     * successful first open are non-throwing and surface via the listener's
     * {@code onError} / {@code onReconnecting} / {@code onReconnect} callbacks.
     *
     * <p>Concurrent calls fold into a single in-flight future rather than opening
     * multiple sockets.</p>
     */
    public CompletableFuture<Void> connect() {
        synchronized (stateLock) {
            if (isConnected()) {
                return CompletableFuture.completedFuture(null);
            }
            if (connectingFuture != null) {
                return connectingFuture;
            }
            userInitiatedClose = false;
            fatalError = null;
            CompletableFuture<Void> f = new CompletableFuture<>();
            connectingFuture = f;
            openSocket(f);
            return f;
        }
    }

    /** True if the underlying socket exists and is not in a closing state. */
    public boolean isConnected() {
        WebSocket s = socket;
        return s != null && !s.isInputClosed() && !s.isOutputClosed();
    }

    /**
     * Close the connection cleanly and disable automatic reconnect. After this
     * the client is inert until {@link #connect()} is called again. Tracked
     * subscriptions are preserved and replayed on the next successful connect;
     * call {@link #reset()} first if you want to discard them.
     */
    public void disconnect() {
        synchronized (stateLock) {
            userInitiatedClose = true;
            cancel(reconnectTask);
            reconnectTask = null;
            stopHeartbeat();
            stopPing();
            reconnectAttempts = 0;
            fatalError = null;
            WebSocket s = socket;
            if (s != null) {
                try {
                    s.sendClose(WebSocket.NORMAL_CLOSURE, "client disconnect");
                } catch (Throwable t) {
                    s.abort();
                }
            }
        }
    }

    /** Subscribe to one symbol. Bare strings may be comma-separated (e.g. {@code "AAPL,MSFT"}). */
    public void subscribe(String symbol) {
        subscribeAll(Collections.singletonList(symbol));
    }

    /** Subscribe to multiple symbols. */
    public void subscribe(String... symbols) {
        subscribeAll(java.util.Arrays.asList(symbols));
    }

    /** Subscribe to a single extended-form symbol. */
    public void subscribe(SubscribeSymbol symbol) {
        subscribeAll(Collections.singletonList(symbol));
    }

    /** Subscribe to a mixed collection of {@code String} and/or {@link SubscribeSymbol} entries. */
    public void subscribeAll(Collection<?> inputs) {
        List<Object> items = normalize(inputs);
        if (items.isEmpty()) return;
        for (Object item : items) {
            subscriptions.put(canonicalKey(item), item);
        }
        send(buildSubscribeFrame("subscribe", items));
    }

    /** Unsubscribe from one symbol. */
    public void unsubscribe(String symbol) {
        unsubscribeAll(Collections.singletonList(symbol));
    }

    /** Unsubscribe from multiple symbols. */
    public void unsubscribe(String... symbols) {
        unsubscribeAll(java.util.Arrays.asList(symbols));
    }

    /** Unsubscribe from a single extended-form symbol. */
    public void unsubscribe(SubscribeSymbol symbol) {
        unsubscribeAll(Collections.singletonList(symbol));
    }

    /** Unsubscribe from a mixed collection of {@code String} and/or {@link SubscribeSymbol} entries. */
    public void unsubscribeAll(Collection<?> inputs) {
        List<Object> items = normalize(inputs);
        if (items.isEmpty()) return;
        for (Object item : items) {
            subscriptions.remove(canonicalKey(item));
        }
        send(buildSubscribeFrame("unsubscribe", items));
    }

    /** Clear local subscription tracking and ask the server to reset. */
    public void reset() {
        subscriptions.clear();
        send(Collections.singletonMap("action", "reset"));
    }

    /** Send a single application-level heartbeat frame. */
    public void heartbeat() {
        send(Collections.singletonMap("action", "heartbeat"));
    }

    // ---- internal: connection lifecycle ----------------------------------

    private void openSocket(CompletableFuture<Void> finalFuture) {
        URI uri;
        try {
            uri = buildUri();
        } catch (RuntimeException ex) {
            failConnect(finalFuture, new TwelvedataWebSocketException.ConnectionException(
                    "Invalid WebSocket URL: " + ex.getMessage(), ex));
            return;
        }
        WebSocket.Builder builder = httpClient.newWebSocketBuilder();
        InternalListener listener = new InternalListener(finalFuture);
        currentListener = listener;
        CompletableFuture<WebSocket> built;
        try {
            built = builder.buildAsync(uri, listener);
        } catch (RuntimeException ex) {
            // E.g. IllegalArgumentException for a bad URI scheme — no socket was created.
            failConnect(finalFuture, new TwelvedataWebSocketException.ConnectionException(
                    "Failed to start WebSocket handshake: " + ex.getMessage(), ex));
            return;
        }
        // The JDK has no built-in handshake timeout — without orTimeout a stuck
        // upgrade hangs the future forever, the reconnect loop never advances,
        // and the client appears dead. orTimeout does NOT cancel the upstream
        // operation, so a late success would otherwise fire onOpen on the
        // orphan listener; the currentListener guard inside InternalListener
        // catches that.
        built.orTimeout(HANDSHAKE_TIMEOUT_MS, TimeUnit.MILLISECONDS).whenComplete((ws, throwable) -> {
            if (throwable != null) {
                Throwable root = unwrap(throwable);
                TwelvedataWebSocketException err = classifyHandshakeFailure(root);
                if (err instanceof TwelvedataWebSocketException.AuthException) {
                    fatalError = err;
                }
                emitError(err);
                failConnect(finalFuture, err);
                return;
            }
            // onOpen has already resolved finalFuture and set socket — nothing to do here.
        });
    }

    private void failConnect(CompletableFuture<Void> finalFuture, TwelvedataWebSocketException err) {
        synchronized (stateLock) {
            if (connectingFuture == finalFuture) {
                connectingFuture = null;
            }
        }
        finalFuture.completeExceptionally(err);
    }

    private void scheduleReconnect() {
        synchronized (stateLock) {
            if (!reconnectConfig.enabled) return;
            if (fatalError != null) return;
            if (userInitiatedClose) return;
            if (reconnectAttempts >= reconnectConfig.maxAttempts) {
                emitError(new TwelvedataWebSocketException.ReconnectException(
                        "Reconnect failed after " + reconnectAttempts + " attempts",
                        reconnectAttempts));
                return;
            }
            int attempt = reconnectAttempts + 1;
            long base = (long) Math.min(
                    reconnectConfig.initialDelayMs * Math.pow(reconnectConfig.backoffFactor, reconnectAttempts),
                    reconnectConfig.maxDelayMs);
            // ±20% jitter so a fleet reconnecting after the same outage doesn't synchronize.
            double jitter = base * 0.2 * (Math.random() * 2 - 1);
            long delay = Math.max(0L, Math.round(base + jitter));
            reconnectAttempts = attempt;
            emit(l -> l.onReconnecting(new ReconnectingEvent(attempt, delay)));

            cancel(reconnectTask);
            reconnectTask = scheduler.schedule(() -> attemptReconnect(attempt), delay, TimeUnit.MILLISECONDS);
        }
    }

    private void attemptReconnect(int attempt) {
        CompletableFuture<Void> f = new CompletableFuture<>();
        f.whenComplete((ok, err) -> {
            if (err == null) {
                emit(l -> l.onReconnect(new ReconnectEvent(attempt)));
                return;
            }
            // No JDK Listener events fire when buildAsync fails (sync, async,
            // or timeout) — there's no onClose to drive the next attempt for
            // us, so reschedule explicitly here. (After a successful onOpen,
            // the close-handler in handleClose drives reconnects instead.)
            if (!userInitiatedClose && fatalError == null) {
                scheduleReconnect();
            }
        });
        openSocket(f);
    }

    // ---- internal: keep-alive --------------------------------------------

    private void startHeartbeat() {
        stopHeartbeat();
        if (heartbeatIntervalMs <= 0) return;
        heartbeatTask = scheduler.scheduleAtFixedRate(
                this::heartbeatSafe, heartbeatIntervalMs, heartbeatIntervalMs, TimeUnit.MILLISECONDS);
    }

    private void heartbeatSafe() {
        try {
            heartbeat();
        } catch (Throwable t) {
            // Don't let one heartbeat failure kill the timer.
        }
    }

    private void stopHeartbeat() {
        cancel(heartbeatTask);
        heartbeatTask = null;
    }

    private void startPing() {
        stopPing();
        if (pingIntervalMs <= 0) return;
        pingTask = scheduler.scheduleAtFixedRate(
                this::sendPing, pingIntervalMs, pingIntervalMs, TimeUnit.MILLISECONDS);
    }

    private void sendPing() {
        WebSocket s = socket;
        if (s == null || s.isOutputClosed()) return;
        try {
            s.sendPing(ByteBuffer.allocate(0));
        } catch (Throwable t) {
            handleDeadConnection();
            return;
        }
        armPongDeadline();
    }

    private void stopPing() {
        cancel(pingTask);
        pingTask = null;
        clearPongDeadline();
    }

    private void armPongDeadline() {
        clearPongDeadline();
        if (pingTimeoutMs <= 0) return;
        pongDeadline = scheduler.schedule(() -> {
            emitError(new TwelvedataWebSocketException.TimeoutException(
                    "No pong received within " + pingTimeoutMs + "ms", pingTimeoutMs));
            handleDeadConnection();
        }, pingTimeoutMs, TimeUnit.MILLISECONDS);
    }

    private void clearPongDeadline() {
        cancel(pongDeadline);
        pongDeadline = null;
    }

    private void handleDeadConnection() {
        WebSocket s = socket;
        if (s == null) return;
        try {
            s.abort();
        } catch (Throwable t) {
            /* fall through */
        }
        // The JDK does NOT invoke Listener.onClose after abort() — drive the
        // close-handler manually. Idempotent if onClose does fire later,
        // because handleClose checks socket identity.
        handleClose(s, 1006, "abnormal closure");
    }

    /**
     * Idempotent close-handler shared by {@link InternalListener#onClose},
     * {@link InternalListener#onError}, and {@link #handleDeadConnection()}.
     * Guarded by socket identity so a late callback from a stale connection
     * cannot tear down a freshly reopened socket.
     */
    private void handleClose(WebSocket s, int code, String reason) {
        synchronized (stateLock) {
            if (socket != s) return;
            socket = null;
            stopHeartbeat();
            stopPing();
        }
        emit(l -> l.onClose(code, reason));
        if (!userInitiatedClose && hasEverConnected && fatalError == null) {
            scheduleReconnect();
        }
    }

    // ---- internal: send / message dispatch -------------------------------

    private void send(Object payload) {
        WebSocket s = socket;
        if (s == null || s.isOutputClosed()) {
            emitError(new TwelvedataWebSocketException.ConnectionException(
                    "Cannot send: WebSocket is not open"));
            return;
        }
        String text;
        try {
            text = mapper.writeValueAsString(payload);
        } catch (Throwable t) {
            emitError(new TwelvedataWebSocketException(
                    "Failed to serialize WebSocket frame: " + t.getMessage(), t));
            return;
        }
        try {
            s.sendText(text, true);
        } catch (Throwable t) {
            emitError(new TwelvedataWebSocketException.ConnectionException(
                    "Failed to send WebSocket frame: " + t.getMessage(), t));
        }
    }

    private void replaySubscriptions() {
        List<Object> items;
        synchronized (subscriptions) {
            if (subscriptions.isEmpty()) return;
            items = new ArrayList<>(subscriptions.values());
        }
        send(buildSubscribeFrame("subscribe", items));
    }

    private void handleMessage(String text) {
        Map<String, Object> raw;
        try {
            @SuppressWarnings("unchecked")
            Map<String, Object> parsed = mapper.readValue(text, Map.class);
            raw = parsed;
        } catch (Throwable t) {
            emitError(new TwelvedataWebSocketException(
                    "Failed to parse WebSocket message: " + t.getMessage(), t));
            return;
        }
        Object eventField = raw.get("event");
        String event = eventField != null ? eventField.toString() : null;
        if ("price".equals(event)) {
            try {
                PriceEvent pe = mapper.convertValue(raw, PriceEvent.class);
                emit(l -> l.onPrice(pe));
            } catch (Throwable t) {
                emitError(new TwelvedataWebSocketException(
                        "Failed to decode price event: " + t.getMessage(), t));
            }
        } else if ("subscribe-status".equals(event)) {
            try {
                SubscribeStatusEvent se = mapper.convertValue(raw, SubscribeStatusEvent.class);
                if (se.getSuccess() == null) se.setSuccess(new ArrayList<>());
                if (se.getFails() == null) se.setFails(new ArrayList<>());
                emit(l -> l.onSubscribeStatus(se));
            } catch (Throwable t) {
                emitError(new TwelvedataWebSocketException(
                        "Failed to decode subscribe-status event: " + t.getMessage(), t));
            }
        } else if ("heartbeat".equals(event)) {
            try {
                HeartbeatEvent he = mapper.convertValue(raw, HeartbeatEvent.class);
                emit(l -> l.onHeartbeat(he));
            } catch (Throwable t) {
                emitError(new TwelvedataWebSocketException(
                        "Failed to decode heartbeat event: " + t.getMessage(), t));
            }
        } else {
            emit(l -> l.onMessage(raw));
        }
    }

    // ---- internal: helpers -----------------------------------------------

    private URI buildUri() {
        URI base = URI.create(url);
        String existingQuery = base.getRawQuery();
        String addition = "apikey=" + URLEncoder.encode(apiKey, StandardCharsets.UTF_8);
        String newQuery = (existingQuery == null || existingQuery.isEmpty())
                ? addition
                : existingQuery + "&" + addition;
        StringBuilder sb = new StringBuilder();
        sb.append(base.getScheme()).append("://").append(base.getRawAuthority());
        if (base.getRawPath() != null) sb.append(base.getRawPath());
        sb.append('?').append(newQuery);
        if (base.getRawFragment() != null) sb.append('#').append(base.getRawFragment());
        return URI.create(sb.toString());
    }

    private static Map<String, Object> buildSubscribeFrame(String action, List<Object> items) {
        Map<String, Object> frame = new LinkedHashMap<>();
        frame.put("action", action);
        Map<String, Object> params = new LinkedHashMap<>();
        params.put("symbols", serializeSymbols(items));
        frame.put("params", params);
        return frame;
    }

    /**
     * Compute the {@code params.symbols} value sent on the wire. A single bare
     * string is sent as-is (so callers can use the comma-separated form
     * documented by Twelvedata); an all-strings array is joined with commas;
     * any object input is sent as a typed list so the server can parse the
     * extended form.
     */
    private static Object serializeSymbols(List<Object> items) {
        if (items.size() == 1 && items.get(0) instanceof String) {
            return items.get(0);
        }
        boolean allStrings = true;
        for (Object i : items) {
            if (!(i instanceof String)) {
                allStrings = false;
                break;
            }
        }
        if (allStrings) {
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < items.size(); i++) {
                if (i > 0) sb.append(',');
                sb.append((String) items.get(i));
            }
            return sb.toString();
        }
        List<Object> out = new ArrayList<>(items.size());
        for (Object i : items) {
            if (i instanceof String) {
                out.add(new SubscribeSymbol((String) i));
            } else {
                out.add(i);
            }
        }
        return out;
    }

    private static List<Object> normalize(Collection<?> inputs) {
        if (inputs == null) return Collections.emptyList();
        List<Object> out = new ArrayList<>();
        for (Object item : inputs) {
            if (item == null) continue;
            if (item instanceof String) {
                String s = (String) item;
                // Split comma-separated tickers so canonical-key dedup works at
                // the individual symbol level (e.g. "AAPL,MSFT" + "AAPL" → {AAPL, MSFT}).
                for (String part : s.split(",")) {
                    String trimmed = part.trim();
                    if (!trimmed.isEmpty()) out.add(trimmed);
                }
            } else if (item instanceof SubscribeSymbol) {
                out.add(item);
            } else {
                throw new IllegalArgumentException(
                        "Unsupported subscription input: " + item.getClass().getName());
            }
        }
        return out;
    }

    private static String canonicalKey(Object item) {
        if (item instanceof String) return "s:" + item;
        return ((SubscribeSymbol) item).canonicalKey();
    }

    /**
     * Inspect a non-101 upgrade response and return the most specific error
     * type. Twelvedata sometimes returns HTTP 200 with a JSON error body for
     * an invalid API key, sometimes 401, sometimes 403; classify from both.
     */
    static TwelvedataWebSocketException classifyUpgradeFailure(int status, String body) {
        long code = status;
        String message = body;
        try {
            if (body != null && !body.isEmpty()) {
                @SuppressWarnings("unchecked")
                Map<String, Object> parsed = new ObjectMapper().readValue(body, Map.class);
                Object c = parsed.get("code");
                if (c instanceof Number) code = ((Number) c).longValue();
                Object m = parsed.get("message");
                if (m instanceof String && !((String) m).isEmpty()) message = (String) m;
            }
        } catch (Throwable t) {
            /* not JSON — fall through */
        }
        if (message == null) message = "HTTP " + status + " from WebSocket upgrade";
        if (message.length() > 200) message = message.substring(0, 200);

        boolean isAuth = code == 401L
                || code == 403L
                || status == 401
                || status == 403
                || message != null && message.toLowerCase().matches(
                        ".*(api[\\s_-]?key|unauthor|forbidden|invalid token).*");
        if (isAuth) {
            return new TwelvedataWebSocketException.AuthException("Authentication failed: " + message);
        }
        return new TwelvedataWebSocketException.ConnectionException(
                "Unexpected server response (HTTP " + status + "): " + message);
    }

    private static TwelvedataWebSocketException classifyHandshakeFailure(Throwable t) {
        if (t instanceof TwelvedataWebSocketException) return (TwelvedataWebSocketException) t;
        if (t instanceof WebSocketHandshakeException) {
            WebSocketHandshakeException ex = (WebSocketHandshakeException) t;
            HttpResponse<?> response = ex.getResponse();
            int status = response != null ? response.statusCode() : 0;
            String body = "";
            if (response != null) {
                Object b = response.body();
                if (b != null) body = b.toString();
            }
            return classifyUpgradeFailure(status, body);
        }
        return new TwelvedataWebSocketException.ConnectionException(
                "Failed to open WebSocket: " + t.getMessage(), t);
    }

    private static Throwable unwrap(Throwable t) {
        while (t instanceof CompletionException && t.getCause() != null) t = t.getCause();
        return t;
    }

    private static String firstNonEmpty(String... values) {
        for (String v : values) {
            if (v != null && !v.isEmpty()) return v;
        }
        return null;
    }

    private static void cancel(ScheduledFuture<?> f) {
        if (f != null) f.cancel(false);
    }

    private static ThreadFactory daemonThreadFactory() {
        return r -> {
            Thread t = new Thread(r, "twelvedata-ws");
            t.setDaemon(true);
            return t;
        };
    }

    private void emitError(TwelvedataWebSocketException err) {
        emit(l -> l.onError(err));
    }

    private void emit(java.util.function.Consumer<TwelvedataWebSocketListener> action) {
        for (TwelvedataWebSocketListener l : listeners) {
            try {
                action.accept(l);
            } catch (Throwable t) {
                /* one listener's failure must not break the dispatch loop */
            }
        }
    }

    // ---- internal: WebSocket.Listener implementation ---------------------

    private final class InternalListener implements WebSocket.Listener {

        private final CompletableFuture<Void> connectFuture;
        private boolean settledConnectFuture;

        InternalListener(CompletableFuture<Void> connectFuture) {
            this.connectFuture = connectFuture;
        }

        /**
         * Late-arriving callbacks from a connection that the client has already
         * abandoned (e.g. handshake-timed-out, then succeeded server-side; or
         * reconnect already started). Such events would clobber the current
         * connection's state, so callers bail out via this check.
         */
        private boolean isStale() {
            return currentListener != this;
        }

        @Override
        public void onOpen(WebSocket webSocket) {
            if (isStale()) {
                // Orphan handshake completed after we moved on — drop the socket.
                try {
                    webSocket.abort();
                } catch (Throwable t) {
                    /* best-effort */
                }
                return;
            }
            socket = webSocket;
            // Request continuous delivery so we don't have to call request(1) per message.
            webSocket.request(Long.MAX_VALUE);
            // Discard any leftover fragment from a previous connection.
            textBuffer.setLength(0);
            reconnectAttempts = 0;
            hasEverConnected = true;
            startHeartbeat();
            startPing();
            replaySubscriptions();
            emit(TwelvedataWebSocketListener::onOpen);
            synchronized (stateLock) {
                if (connectingFuture == connectFuture) {
                    connectingFuture = null;
                }
            }
            if (!settledConnectFuture) {
                settledConnectFuture = true;
                connectFuture.complete(null);
            }
        }

        @Override
        public CompletionStage<?> onText(WebSocket webSocket, CharSequence data, boolean last) {
            if (isStale()) return null;
            textBuffer.append(data);
            if (last) {
                String full = textBuffer.toString();
                textBuffer.setLength(0);
                handleMessage(full);
            }
            return null;
        }

        @Override
        public CompletionStage<?> onPing(WebSocket webSocket, ByteBuffer message) {
            // The JDK auto-replies with pong; nothing to do.
            return null;
        }

        @Override
        public CompletionStage<?> onPong(WebSocket webSocket, ByteBuffer message) {
            if (isStale()) return null;
            clearPongDeadline();
            return null;
        }

        @Override
        public CompletionStage<?> onClose(WebSocket webSocket, int statusCode, String reason) {
            if (isStale()) return null;
            handleClose(webSocket, statusCode, reason);
            return null;
        }

        @Override
        public void onError(WebSocket webSocket, Throwable error) {
            if (isStale()) return;
            // Pre-open errors are surfaced via the buildAsync future. Post-open
            // errors lead here; deliver to the listener. JDK docs warn that
            // onClose may not follow onError, so drive the close-path ourselves.
            emitError(new TwelvedataWebSocketException.ConnectionException(
                    "WebSocket error: " + (error != null ? error.getMessage() : "unknown"), error));
            handleClose(webSocket, 1006, "transport error");
        }
    }

    private static final class ResolvedReconnectConfig {
        final boolean enabled;
        final long initialDelayMs;
        final long maxDelayMs;
        final int maxAttempts;
        final double backoffFactor;

        ResolvedReconnectConfig(boolean enabled, long initialDelayMs, long maxDelayMs,
                                int maxAttempts, double backoffFactor) {
            this.enabled = enabled;
            this.initialDelayMs = initialDelayMs;
            this.maxDelayMs = maxDelayMs;
            this.maxAttempts = maxAttempts;
            this.backoffFactor = backoffFactor;
        }

        static ResolvedReconnectConfig from(ReconnectOptions o) {
            if (o == null) {
                return new ResolvedReconnectConfig(false,
                        WebSocketConstants.DEFAULT_RECONNECT_INITIAL_DELAY_MS,
                        WebSocketConstants.DEFAULT_RECONNECT_MAX_DELAY_MS,
                        0,
                        WebSocketConstants.DEFAULT_RECONNECT_BACKOFF_FACTOR);
            }
            return new ResolvedReconnectConfig(true,
                    o.getInitialDelayMs(),
                    o.getMaxDelayMs(),
                    o.getMaxAttempts(),
                    o.getBackoffFactor());
        }
    }
}
