/*
 * Twelve Data API client for Java
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twelvedata.client.ws;

import java.util.Map;

/**
 * Listener interface for events emitted by {@link TwelvedataWebSocketClient}.
 *
 * <p>All callbacks are {@code default} no-ops so callers override only the
 * events they care about. Unknown server-side events fall through to
 * {@link #onMessage} so the wrapper does not silently swallow new event types.</p>
 *
 * <p>Listeners are invoked sequentially on the client's internal scheduler thread.
 * Long-running work in a callback delays subsequent events; offload to a separate
 * thread/executor if needed.</p>
 */
public interface TwelvedataWebSocketListener {

    /** Fired after the underlying WebSocket reaches the OPEN state. */
    default void onOpen() {}

    /** Fired after the WebSocket has closed. */
    default void onClose(int code, String reason) {}

    /**
     * Fired for any non-fatal error after a successful connect. Pre-connect
     * failures are surfaced via {@link TwelvedataWebSocketClient#connect()}'s
     * future instead.
     */
    default void onError(TwelvedataWebSocketException error) {}

    /** Catch-all for server-side events that don't match a typed callback. */
    default void onMessage(Map<String, Object> raw) {}

    /** Real-time price tick. */
    default void onPrice(PriceEvent event) {}

    /** Server response to a subscribe / unsubscribe action. */
    default void onSubscribeStatus(SubscribeStatusEvent event) {}

    /** Server acknowledgement of an application-level heartbeat. */
    default void onHeartbeat(HeartbeatEvent event) {}

    /** Fired before each reconnect attempt. */
    default void onReconnecting(ReconnectingEvent event) {}

    /** Fired after a reconnect attempt has succeeded. */
    default void onReconnect(ReconnectEvent event) {}
}
