/*
 * Twelve Data API client for Java
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twelvedata.client.ws;

/**
 * Constructor options for {@link TwelvedataWebSocketClient}. Built with
 * {@link #builder()}; every knob has a default in {@link WebSocketConstants}.
 *
 * <p>The API key is resolved in this order: explicit {@link Builder#apiKey(String)}
 * argument, then the {@code TWELVEDATA_API_KEY} env variable. If neither is
 * available the client constructor throws
 * {@link TwelvedataWebSocketException.AuthException} synchronously.</p>
 */
public final class TwelvedataWebSocketOptions {

    private final String apiKey;
    private final String url;
    private final long heartbeatIntervalMs;
    private final long pingIntervalMs;
    private final long pingTimeoutMs;
    private final ReconnectOptions reconnect;

    private TwelvedataWebSocketOptions(Builder b) {
        this.apiKey = b.apiKey;
        this.url = b.url;
        this.heartbeatIntervalMs = b.heartbeatIntervalMs;
        this.pingIntervalMs = b.pingIntervalMs;
        this.pingTimeoutMs = b.pingTimeoutMs;
        this.reconnect = b.reconnect;
    }

    public String getApiKey() {
        return apiKey;
    }

    public String getUrl() {
        return url;
    }

    public long getHeartbeatIntervalMs() {
        return heartbeatIntervalMs;
    }

    public long getPingIntervalMs() {
        return pingIntervalMs;
    }

    public long getPingTimeoutMs() {
        return pingTimeoutMs;
    }

    /** {@code null} means automatic reconnection is disabled. */
    public ReconnectOptions getReconnect() {
        return reconnect;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {

        private String apiKey;
        private String url = WebSocketConstants.DEFAULT_WS_URL;
        private long heartbeatIntervalMs = WebSocketConstants.DEFAULT_HEARTBEAT_INTERVAL_MS;
        private long pingIntervalMs = WebSocketConstants.DEFAULT_PING_INTERVAL_MS;
        private long pingTimeoutMs = WebSocketConstants.DEFAULT_PING_TIMEOUT_MS;
        private ReconnectOptions reconnect = ReconnectOptions.builder().build();

        /** Twelvedata API key. Falls back to {@code TWELVEDATA_API_KEY} env variable when null. */
        public Builder apiKey(String v) {
            this.apiKey = v;
            return this;
        }

        /** Override the WebSocket endpoint URL. Defaults to {@link WebSocketConstants#DEFAULT_WS_URL}. */
        public Builder url(String v) {
            this.url = v;
            return this;
        }

        /** Interval between application-level heartbeat frames, in milliseconds. Set to {@code 0} to disable. */
        public Builder heartbeatIntervalMs(long v) {
            this.heartbeatIntervalMs = v;
            return this;
        }

        /** Interval between WebSocket-protocol ping frames, in milliseconds. Set to {@code 0} to disable. */
        public Builder pingIntervalMs(long v) {
            this.pingIntervalMs = v;
            return this;
        }

        /** Maximum time to wait for a pong reply before reconnecting, in milliseconds. */
        public Builder pingTimeoutMs(long v) {
            this.pingTimeoutMs = v;
            return this;
        }

        /** Reconnect strategy. Pass {@code null} to disable automatic reconnection. */
        public Builder reconnect(ReconnectOptions v) {
            this.reconnect = v;
            return this;
        }

        public TwelvedataWebSocketOptions build() {
            return new TwelvedataWebSocketOptions(this);
        }
    }
}
