/*
 * Twelve Data API client for Java
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twelvedata.client.ws;

/**
 * Base exception for the Twelvedata WebSocket client.
 *
 * <p>Surfaces in two places:
 * <ul>
 *   <li>{@link TwelvedataWebSocketClient#connect()} completes exceptionally
 *       with the first error encountered while opening the socket.</li>
 *   <li>Any error after a successful connection is delivered via
 *       {@link TwelvedataWebSocketListener#onError(TwelvedataWebSocketException)}.</li>
 * </ul>
 *
 * <p>Fatal errors (e.g. an invalid API key) suppress the auto-reconnect loop
 * so the client fails fast instead of retrying indefinitely.</p>
 */
public class TwelvedataWebSocketException extends RuntimeException {

    public TwelvedataWebSocketException(String message) {
        super(message);
    }

    public TwelvedataWebSocketException(String message, Throwable cause) {
        super(message, cause);
    }

    /** Thrown when the API key is missing or rejected by the server during the upgrade handshake. Not retried. */
    public static class AuthException extends TwelvedataWebSocketException {
        public AuthException(String message) {
            super(message);
        }

        public AuthException(String message, Throwable cause) {
            super(message, cause);
        }
    }

    /** Thrown when the underlying socket cannot be opened, a send fails, or the server returns an unexpected non-auth response. */
    public static class ConnectionException extends TwelvedataWebSocketException {
        public ConnectionException(String message) {
            super(message);
        }

        public ConnectionException(String message, Throwable cause) {
            super(message, cause);
        }
    }

    /** Thrown when no pong reply is received within the configured timeout. Triggers a reconnect. */
    public static class TimeoutException extends TwelvedataWebSocketException {

        private final long timeoutMs;

        public TimeoutException(String message, long timeoutMs) {
            super(message);
            this.timeoutMs = timeoutMs;
        }

        /** Configured pong timeout that was exceeded, in milliseconds. */
        public long getTimeoutMs() {
            return timeoutMs;
        }
    }

    /** Thrown when reconnect attempts have been exhausted (hit {@code reconnect.maxAttempts}). */
    public static class ReconnectException extends TwelvedataWebSocketException {

        private final int attempts;

        public ReconnectException(String message, int attempts) {
            super(message);
            this.attempts = attempts;
        }

        /** Number of reconnect attempts made before giving up. */
        public int getAttempts() {
            return attempts;
        }
    }
}
