/*
 * Twelve Data API client for Java
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twelvedata.client.ws;

/**
 * Default constants for the Twelvedata WebSocket client.
 *
 * <p>Every default that {@link TwelvedataWebSocketClient} reads from
 * {@link TwelvedataWebSocketOptions} is exposed here so that callers can
 * reference one knob by name when overriding another.</p>
 */
public final class WebSocketConstants {

    /** Default WebSocket endpoint for real-time price streaming. */
    public static final String DEFAULT_WS_URL = "wss://ws.twelvedata.com/v1/quotes/price";

    /**
     * How often to send the application-level {@code {"action":"heartbeat"}} frame.
     * Twelve Data recommends ~10 seconds to keep the connection stable.
     */
    public static final long DEFAULT_HEARTBEAT_INTERVAL_MS = 10_000L;

    /** How often to send a WebSocket-protocol ping frame. */
    public static final long DEFAULT_PING_INTERVAL_MS = 30_000L;

    /**
     * Maximum time to wait for a pong reply before treating the connection as
     * dead and forcing a reconnect.
     */
    public static final long DEFAULT_PING_TIMEOUT_MS = 10_000L;

    /** Initial delay between reconnect attempts, in milliseconds. */
    public static final long DEFAULT_RECONNECT_INITIAL_DELAY_MS = 1_000L;

    /** Upper bound on the reconnect delay, in milliseconds. */
    public static final long DEFAULT_RECONNECT_MAX_DELAY_MS = 30_000L;

    /**
     * Maximum number of reconnect attempts before giving up. Use
     * {@link Integer#MAX_VALUE} to retry effectively forever.
     */
    public static final int DEFAULT_RECONNECT_MAX_ATTEMPTS = 10;

    /** Multiplier applied to the reconnect delay after each failed attempt. */
    public static final double DEFAULT_RECONNECT_BACKOFF_FACTOR = 2.0;

    private WebSocketConstants() {}
}
